sudo: false

language: node_js

node_js:
  - "node"

services:
  - postgresql
  - redis-server

before_script:
  - psql -c 'create database test;' -U postgres

install:
  # install deps
  - npm install
script:
  - npm test
  - npm build

after_success:
  - npm run coverage
