version: "3"
services:
  db:
    restart: always
    env_file:
      - .env
    image: postgres
    environment:
      - POSTGRES_USER=${PG_USER}
      - POSTGRES_PASSWORD=${PG_PASSWORD}
      - POSTGRES_DB=${PG_DB}
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - ${DB_PORT}:${DB_PORT}
    networks:
      - webnet
  redis:
    image: redis
    networks:
      - webnet
  backend:
    build:
      context: .
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
    entrypoint: ["/bin/bash", "./entrypoint.sh"]
    depends_on:
      - db
      - redis
    networks:
      - webnet
networks:
  webnet:
